[package]
name = "native_gl_surface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]

[dependencies]
android_logger = "0.14.1"
glow = "0.15.0"
jni = "0.21.1"
log = "0.4.22"
ndk-context = "0.1.1"
parking_lot = "0.12.3"
